#!/usr/bin/env bash

###############################################################################
#                           DECLARE CONSTANTS                                 #
###############################################################################

HOSTNAME=$(hostname -s)
SERIAL_NUMBER=$(ioreg -c IOPlatformExpertDevice -d 2 | awk -F\" '/IOPlatformSerialNumber/{print $(NF-1)}')

MOUNT="/Volumes/MunkiRepo"
MANIFESTS_DIR="$MOUNT/manifests"
MANIFEST_PLIST="$MANIFESTS_DIR/$SERIAL_NUMBER"

CATALOGS=(
    "Choose catalogs to add $SERIAL_NUMBER to:"
    "Creative"
    "Deployments"
    "IT_Testing"
    "Mobile"
    "SportsAndEnts"
)

###############################################################################
#                                USAGE FUNCTION                               #
###############################################################################

usage () {
    echo "
$(basename "$0") [AFS or Samba Share URL]

AUTOMATED MUNKI CLIENT CONFIGURATION
------------------------------------

This script must be run as root.

It takes an AFS or Samba Share as an optional argument. If none are given you
will be prompted for them.

It carries out the following tasks:

  1) Mount Munki repository via Samba or AFS at /Volumes/MunkiRepo.
  2) Create new Munki manifest with machine's serial number as name.
  3) Choose catalogs/included manifests to add newly created manifest to.
  4) Check for and display available software.
  5) Install all available software.
"
}

###############################################################################
#                           SHARE MOUNTING FUNCTIONS                          #
###############################################################################

mountshare () {
    local share="$1"

    # .* is egrep AND/this search string followed by this search string.
    if ! mount | grep -Eq "$MOUNT"; then
	checkdir "$MOUNT"
	# escape spaces in url encoding - http://www.degraeve.com/reference/urlencoding.php
	if ! mount -t smbfs "${share// /%20}" "$MOUNT"; then
	    echo "Could not mount $share at $MOUNT. Aborting."
	    exit 1
	fi
    fi
}

# read in mount_smbfs url if no arg provided
getshare () {
    local arg="$1" share host path user pass

    if [[ -z "$arg" ]]; then
	# -r to avoid mangled backslashes, -e for readline, -s for no echo
	read -rep "Share Hostname or IP Address: " host
	read -rep "Share Path: " path
	share="//$host/$path"
    else
	share="$arg"
    fi

    mountshare "$share"
}

###############################################################################
#                             USEFUL PORTABLE FUNCTIONS                       #
###############################################################################

# infinite loop to get simple user input
ask () {
    local question="$1"

    while :; do
	# -e for readline bindings
	# -r to not mangle backslashes
	# -n 1 for execution without return
	read -rep "$question" ans;
	case $ans in
	    [Yy]*)
		return 0
		;;
	    [Nn]*)
		return 1
		;;
	    [Qq]*)
		echo
		exit 0
		;;
	    *)
		echo
		echo "$ans is invalid. Enter (y)es, (n)o or (q)uit."
		echo
		;;
	esac
    done
}

# check for existence of a directory and if it doesn't exist create it.
checkdir () {
    local dir="$1"

    if [[ ! -d "$dir" ]]; then
	if ! mkdir -p "$dir"; then
	    echo "Error creating $dir";
	    exit 1
	fi
    fi
}

# check if running as root
checkroot () {
    if [[ "$(id -u)" -ne 0 ]]; then
	echo;
	echo "This script must be run as root."
	usage
	exit 1
    fi
}

# takes an array as an argument and creates a checkbox selection menu for each
# element of array.
#
# returns new array of selected items.
get_selection () {
    string="$1"
    shift # short for shift 1 - so rest of items become menu items
    selectall=false options=("$@") choices=()

    while :; do
	clear
	echo
	echo "$string"
	echo
	echo "Enter the corresponding number to toggle a selection."
	echo "Enter a to toggle all, r to reset selection or q to quit."
	echo
	for i in "${!options[@]}"; do
	    printf "%3d%s) %s\\n" $((i+1)) "${choices[i]:- }" "${options[i]}"
	done
	echo

	[[ "$msg" ]] && { echo "$msg"; echo; }

	read -rep "----> " input

	case "$input" in
	    A|a)
		if "$selectall"; then
		    for i in "${!options[@]}"; do
			choices[i]=""
		    done
		    selectall=false
		else
		    for i in "${!options[@]}"; do
			choices[i]="+"
		    done
		    selectall=true
		fi
		;;
	    Q|q)
		break
		;;
	    R|r)
		for i in "${!options[@]}"; do
		    choices[i]=""
		done
		;;
	    *)
		# regex to catch digits between 1-99, but number must be less than size of array
		if ! [[ "$input" =~ ^[1-9]$|^[1-9][0-9]+$ && "$input" -le "${#options[@]}" ]]; then
		    msg="Invalid option: $input"
		    continue
		fi
		((input--))
		if [[ "${choices[input]}" ]]; then
		    choices[input]=""
		else
		    choices[input]="+"
		fi
		for i in "${!options[@]}"; do
		    if [[ "${choices[i]}" == "" ]]; then
			selectall=false
		    elif [[ "${choices[i]}" == "+" ]]; then
			selectall=true
		    fi
		done
		;;
	esac
    done
    for i in "${!options[@]}"; do
	[[ "${choices[i]}" ]] && selected+=("${options[i]}")
    done
}

# provide user feedback for long running commands.
spinner () {
    local spin pid="$1" str="$2"
    spin='-\|/'
    i=0
    while ps -p "$pid" &> /dev/null; do
	local -i i=$(( (i+1) %4 ))
	printf "\\r%s: ${spin:$i:1} " "$str"
	sleep .1
    done
    # 79 expansions of the space character to blank last line to standard terminal widths
    printf "\\r"; printf " %0.s" {0..79}
}

###############################################################################
#                         MUNKI MANIPULATION FUNCTIONS                        #
###############################################################################

configure () {
    manifestutil --configure
}

get_catalogs () {
    get_selection "${CATALOGS[@]}"
    SELECTED_CATALOGS=("${selected[@]}")
    unset selected
}

add_catalogs () {
    for key in "${!SELECTED_CATALOGS[@]}"; do
	value="${SELECTED_CATALOGS[$key]}"
	echo "Adding $value to catalogs of $SERIAL_NUMBER..."
	plutil -insert catalogs."$key" -string "$value" "$MANIFEST_PLIST"
	echo "Adding $value to included manifests of $SERIAL_NUMBER..."
	plutil -insert included_manifests."$key" -string "$value" "$MANIFEST_PLIST"
    done
}

write_manifest () {
    read -rep "Enter a user name: " user
    /usr/libexec/PlistBuddy -c "Add :catalogs array" "$MANIFEST_PLIST" > /dev/null
    /usr/libexec/PlistBuddy -c "Add :display_name string $HOSTNAME" "$MANIFEST_PLIST"
    /usr/libexec/PlistBuddy -c "Add :included_manifests array" "$MANIFEST_PLIST"
    /usr/libexec/PlistBuddy -c "Add :managed_installs array" "$MANIFEST_PLIST"
    /usr/libexec/PlistBuddy -c "Add :managed_uninstalls array" "$MANIFEST_PLIST"
    /usr/libexec/PlistBuddy -c "Add :user string $user" "$MANIFEST_PLIST"
}

make_manifest () {
    local sanityq="$SERIAL_NUMBER already exists. Are you sure you want to overwrite it?! "

    if [[ -d "$MANIFESTS_DIR" ]]; then
	if [[ -f "$MANIFEST_PLIST" ]]; then
	    if ask "$sanityq"; then
		rm "$MANIFEST_PLIST"
		write_manifest
	    else
		echo "Leaving $MANIFEST_PLIST unchanged."
	    fi
	else
	    write_manifest
	fi
    else
	echo "Cannot find $MANIFESTS_DIR. Is the repository mounted?"
    fi
}

display_manifest () {
    echo "Newly created manifest details:"
    manifestutil display-manifest "$SERIAL_NUMBER"
}

###############################################################################
#                                MAIN FUNCTION                                #
###############################################################################

main () {
    local share="$1"
    local makeq="Create new manifest? "
    local addcatq="Add catalogs to manifest? "
    local addplistq="Add display name and user fields to manifest? "
    local checkq="Check for available software? "
    local installq="Install all available software? "

    clear
    checkroot
    getshare "$share"
    echo
    configure
    echo
    ask "$makeq" && make_manifest
    echo
    ask "$addcatq" && { get_catalogs; clear; echo; add_catalogs; }
    echo
    display_manifest
    echo
    if ask "$checkq"; then
	echo
	software=("$(managedsoftwareupdate --checkonly | awk '/\+/ {print $2}')")
	if [[ $(echo "${#software[@]}") =~ ^\s+$ ]]; then
	    echo "Available Managed Installs:"
	    echo
	    for i in "${software[@]}"; do
		printf "\\t%s\\n" "$i"
	    done
	    echo
	    if ask "$installq"; then
		managedsoftwareupdate --installonly | sed '1,4d;$d' # get rid of output header & footer
	    fi
	else
	    echo "You have all available managed installs."
	    echo "Please check the Managed Software Center app to browse optional installs."
	fi
	echo
    fi
}

###############################################################################
#                                     RUN!                                    #
###############################################################################

main "$@"
