#!/usr/bin/env bash

SERIAL_NUMBER=$(ioreg -c IOPlatformExpertDevice -d 2 | awk -F\" '/IOPlatformSerialNumber/{print $(NF-1)}')

CATALOGS=(
    "Choose catalogs to add $SERIAL_NUMBER to:"
    "all"
    "Creative"
    "Deployments"
    "IT_Testing"
    "Mobile"
    "SportsAndEnts"
)

MANIFESTS=(
    "Choose reference manifests to include for $SERIAL_NUMBER:"
    "Creative"
    "Deployment"
    "ITTesting"
    "Mobile"
    "SportsAndEnts"
)

usage () {
    echo "
$(basename "$0") [OPTION]

AUTOMATED MUNKI CLIENT CONFIGURATION
------------------------------------

This script must be run with one of the following options.

Options:
  -a, --automate	Automate all tasks without prompting.
  -i, --interactive	Ask before each task.

Tasks:
  1) Create new Munki manifest with machine's serial number as name.
  2) Choose catalogs to add newly created manifest to.
  3) Choose included manifests to add to newly created manifest.
  4) Check for and display available software (-i only)
  5) Install all available software.
"
}

# infinite loop to get simple user input
ask () {
    local question="$1"

    while :; do
	# -e for readline bindings
	# -r to not mangle backslashes
	# -n 1 for execution without return
	read -n 1 -rep "$question" ans;
	case $ans in
	    y|Y)
		return 0
		;;
	    n|N)
		return 1
		;;
	    q|Q)
		clear
		exit 0
		;;
	    *)
		echo
		echo "$ans is invalid. Enter (y)es, (n)o or (q)uit."
		echo
		;;
	esac
    done
}

# takes an array as an argument and creates a checkbox selection menu for each
# element of array.
#
# returns new array of selected items.
get_selection () {
    string="$1"
    shift # short for shift 1 - so rest of items become menu items
    selectall=false options=("$@") choices=()

    while :; do
	clear
	echo
	echo "$string"
	echo
	echo "Enter the corresponding number to toggle a selection."
	echo "Enter a to toggle all, r to reset selection or q to quit."
	echo
	for i in "${!options[@]}"; do
	    printf "%3d%s) %s\n" $((i+1)) "${choices[i]:- }" "${options[i]}"
	done
	echo

	[[ "$msg" ]] && { echo "$msg"; echo; }

	read -rep "----> " input

	case "$input" in
	    A|a)
		if "$selectall"; then
		    for i in "${!options[@]}"; do
			choices[i]=""
		    done
		    selectall=false
		else
		    for i in "${!options[@]}"; do
			choices[i]="+"
		    done
		    selectall=true
		fi
		;;
	    Q|q)
		break
		;;
	    R|r)
		for i in "${!options[@]}"; do
		    choices[i]=""
		done
		;;
	    *)
		# regex to catch digits between 1-99, but number must be less than size of array
		if ! [[ "$input" =~ ^[1-9]$|^[1-9][0-9]+$ && "$input" -le "${#options[@]}" ]]; then
		    msg="Invalid option: $input"
		    continue
		fi
		((input--))
		if [[ "${choices[input]}" ]]; then
		    choices[input]=""
		else
		    choices[input]="+"
		fi
		for i in "${!options[@]}"; do
		    if [[ "${choices[i]}" == "" ]]; then
			selectall=false
		    elif [[ "${choices[i]}" == "+" ]]; then
			selectall=true
		    fi
		done
		;;
	esac
    done
    for i in "${!options[@]}"; do
	[[ "${choices[i]}" ]] && selected+=("${options[i]}")
    done
}

make_manifest () {
    echo "Creating new manifest called $SERIAL_NUMBER"
    manifestutil new-manifest "$SERIAL_NUMBER"
}

get_catalogs () {
    get_selection "${CATALOGS[@]}"
    SELECTED_CATALOGS=("${selected[@]}")
    unset selected
}

get_manifests () {
    get_selection "${MANIFESTS[@]}"
    SELECTED_MANIFESTS=("${selected[@]}")
    unset selected
}

add_catalogs () {
    for c in "${SELECTED_CATALOGS[@]}"; do
	echo "Adding $SERIAL_NUMBER to $c catalog..."
	manifestutil add-catalog "$c" --manifest "$SERIAL_NUMBER"
    done
}

add_manifests () {
    for m in "${SELECTED_MANIFESTS[@]}"; do
	echo "Including $m in $SERIAL_NUMBER manifest..."
	manifestutil add-included-manifest "$m" --manifest "$SERIAL_NUMBER"
    done
}

make_catalogs () {
    echo "Making catalogs..."
    makecatalogs &>/dev/null
}

display_manifest () {
    echo "Newly created manifest details:"
    manifestutil display-manifest "$SERIAL_NUMBER"
}

main () {
    makeq="Would you like to create a new manifest? "
    addcatq="Would you like to add catalogs to this manifest? "
    addmanq="Would you like to add included manifests to this manifest? "
    checkq="Would you like to check for available software? "
    installq="Would you like to install all available software? "

    case "$1" in
	-a|--automate)
	    clear
	    echo
	    make_manifest
	    echo
	    get_catalogs
	    echo
	    get_manifests
	    clear
	    echo
	    add_catalogs
	    echo
	    add_manifests
	    echo
	    make_catalogs
	    echo
	    display_manifest
	    echo
	    sudo managedsoftwareupdate --installonly
	    echo
	    ;;
	-i|--interactive)
	    clear
	    echo
	    ask "$makeq" && make_manifest
	    echo
	    ask "$addcatq" && { get_catalogs; clear; echo; add_catalogs; sleep 2; }
	    echo
	    ask "$addmanq" && { get_manifests; clear; echo; add_manifests; sleep 2; }
	    echo
	    display_manifest
	    echo
	    if ask "$checkq"; then
		echo
		echo "Checking for available software..."
		echo
		software=($(sudo managedsoftwareupdate --checkonly | awk '/\+/ {print $2}'))
		echo "Available Software:"
		echo
		for i in "${software[@]}"; do
		    printf "\t%s\n" "$i"
		done
	    fi
	    echo
	    if ask "$installq"; then
		sudo managedsoftwareupdate --installonly
	    fi
	    echo
	    ;;
	-h|--help)
	    usage
	    ;;
	*)
	    echo
	    echo "INVALID OPTION."
	    usage
	    ;;
    esac
}

main "$@"
